export const PageIndex = {
	//key				filename					permissions
	about:				["about",					false],
	action:				["action",					["write"]],
	admin:				["admin_home",				["*"]],
	alarms:				["alarms",					["write"]],
	appInstall:			["app_install",				false],
	attend:				["attend",					false],
	backups:			["backups",					["write"]],
	chart:				["chart",					["write", "read"]],
	charts:				["charts",					["write"]],
	chartEdit:			["chart_edit",				["write", "read"]],
	consent:			["consent",					false],
	dataList:			["data_list",				["read"]],
	dateRange:			["date_range",				["write"]],
	dataView:			["data_view",				["read"]],
	dataStatistics:		["data_statistics",			["read"]],
	errorList:			["error_list",				[]],
	errorView:			["error_view",				[]],
	init_esmira:		["init_esmira",				false],
	input:				["input",					["write"]],
	legal:				["legal",					false],
	login:				["login",					false],
	messages:			["messages",				["msg"]],
	msg:				["msg",						["msg"]],
	pageSettings:		["page_settings",			["write"]],
	participant:		["participant",				false],
	publish:			["publish",					["write"]],
	qEdit:				["questionnaire_edit",		["write"]],
	settings:			["settings",				false],
	screenshots:		["screenshots",				false],
	serverStatistics:	["server_statistics",		false],
	source:				["source",					["write"]],
	statistics:			["statistics",				false],
	studies:			["studies",					false],
	studyEdit:			["study_edit",				["write"]],
	studyDesc:			["study_description",		["write"]],
	studySettings:		["study_settings",			["write"]],
	sumStudy:			["summary_study",			["read"]],
	sumScores:			["sumscores",				["write"]],
	sumScore:			["sumscore",				["write"]],
	sumUser:			["summary_user",			["read"]],
	sumUserList:		["summary_user_list",		["read"]],
	sumWeb:				["summary_web",				["read"]],
	sOverview:			["study_overview",			false],
	trigger:			["trigger",					["write"]],
	home:				["home",					false],
	userList:			["user_list",				[]],
	userView:			["user_view",				[]]
};


// export const PageIndex = {
// 	//key				filename					needs login
// 	about:				["about",					false],
// 	action:				["action",					true],
// 	admin:				["admin_home",				true],
// 	alarms:				["alarms",					true],
// 	appInstall:			["app_install",				false],
// 	attend:				["attend",					false],
// 	backups:			["backups",					true],
// 	chart:				["chart",					true],
// 	charts:				["charts",					true],
// 	chartEdit:			["chart_edit",				true],
// 	consent:			["consent",					true],
// 	dataList:			["data_list",				true],
// 	dateRange:			["date_range",				true],
// 	dataView:			["data_view",				true],
// 	dataStatistics:		["data_statistics",			true],
// 	errorList:			["error_list",				true],
// 	errorView:			["error_view",				true],
// 	init_esmira:		["init_esmira",				false],
// 	input:				["input",					true],
// 	legal:				["legal",					true],
// 	login:				["login",					false],
// 	messages:			["messages",				true],
// 	msg:				["msg",						true],
// 	pageSettings:		["page_settings",			true],
// 	participant:		["participant",				false],
// 	publish:			["publish",					true],
// 	qEdit:				["questionnaire_edit",		true],
// 	questionnaires:		["questionnaires",			true],
// 	settings:			["settings",				false],
// 	screenshots:		["screenshots",				false],
// 	serverStatistics:	["server_statistics",		false],
// 	source:				["source",					true],
// 	statistics:			["statistics",				false],
// 	studies:			["studies",					false],
// 	studyEdit:			["study_edit",				true],
// 	studyDesc:			["study_description",		true],
// 	studySettings:		["study_settings",			true],
// 	sumStudy:			["summary_study",			true],
// 	sumUser:			["summary_user",			true],
// 	sumUserList:		["summary_user_list",		true],
// 	sumScores:			["sumscores",				true],
// 	sumScore:			["sumscore",				true],
// 	sumWeb:				["summary_web",				true],
// 	sOverview:			["study_overview",			true],
// 	trigger:			["trigger",					true],
// 	home:				["home",					false],
// 	userList:			["user_list",				true],
// 	userView:			["user_view",				true]
// };